require: rubocop-rspec

AllCops:
  RunRailsCops: true
  DisplayCopNames: true
  Include:
    - '**/Rakefile'

Metrics/LineLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Exclude:
    - 'app/controllers/generic_files_controller.rb'

Metrics/PerceivedComplexity:
  Exclude:
    - 'app/controllers/generic_files_controller.rb'

Metrics/MethodLength:
  Enabled: false

Metrics/ClassLength:
  Exclude:
    - 'lib/aic.rb'
    - 'lib/aic_type.rb'
    - 'app/controllers/catalog_controller.rb'

Metrics/ModuleLength:
  Exclude:
    - 'spec/support/list_loader.rb'

Style/BlockDelimiters:
  Exclude:
    - 'spec/**/*'

Style/BlockEndNewline:
  Exclude:
    - 'spec/**/*'

Style/MultilineBlockLayout:
  Exclude:
    - 'spec/**/*'

Style/IndentationConsistency:
  EnforcedStyle: rails

Style/CollectionMethods:
  PreferredMethods:
    collect: 'map'
    collect!: 'map!'
    inject: 'reduce'
    detect: 'find'
    find_all: 'select'

Style/WordArray:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/HashSyntax:
  Exclude:

Style/LineEndConcatenation:
  Exclude:

Style/PredicateName:
  Exclude:

Style/GlobalVars:
  Exclude:
    - 'spec/**/*'
    - 'config/initializers/redis_config.rb'

Style/SingleLineBlockParams:
  Enabled: false

Style/ClassVars:
  Exclude:

Style/SignalException:
  Enabled: false

Style/FileName:
  Exclude:

Style/VariableName:
  Exclude:

Style/GuardClause:
  Exclude:
    - 'app/controllers/generic_files_controller.rb'

Rails/Output:
  Exclude:

Rails/Date:
  Enabled: false

Rails/TimeZone:
  Enabled: false

Rails/HasAndBelongsToMany:
  Enabled: false

Rails/FindBy:
  Enabled: false

Rails/Validation:
  Enabled: false

RSpec/ExampleWording:
  CustomTransform:
    be: is
    have: has
    not: does not
    NOT: does NOT
  IgnoredWords:
    - only

RSpec/FilePath:
  Enabled: false

RSpec/InstanceVariable:
  Enabled: false

RSpec/DescribeClass:
  Exclude:
    - 'spec/**/*'
