language: ruby
cache: bundler
sudo: false
rvm:
  - 2.2
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
notifications:
  email:
    recipients:
      - "amsterdamos@gmail.com"
    on_success: "change"
    on_failure: "always"
services:
  - redis-server
before_script:
  - jdk_switcher use oraclejdk8
