pref_label: "Conservation Image Type"
description: "Technical image type."
members:
  - pref_label: "XRF"
    description: ""
  - pref_label: "FTIR"
    description: ""
  - pref_label: "FT-RAMAN"
    description: ""
  - pref_label: "RAMAN"
    description: ""
  - pref_label: "Sampling Map"
    description: ""
  - pref_label: "SEM/EDX"
    description: ""
  - pref_label: "GC/MS"
    description: ""
  - pref_label: "Micrograph"
    description: ""
  - pref_label: "DIC"
    description: ""