pref_label: "Light Type"
description: "Light type used to capture the image."
members:
  - pref_label: "Transmitted Light"
    description: ""
  - pref_label: "X-Ray"
    description: ""
  - pref_label: "X-Ray Rob Erdman"
    description: ""
  - pref_label: "UV"
    description: ""
  - pref_label: "Normal Light"
    description: ""
  - pref_label: "Raking Light"
    description: ""
  - pref_label: "Axial Light"
    description: ""
  - pref_label: "Polarized Light"
    description: ""
  - pref_label: "Reflected Infrared"
    description: ""
  - pref_label: "Transmitted Infrared"
    description: ""
