pref_label: "Document Type"
description: "Select one document type from the hierarchy."
members:
  - pref_label: "General"
    description: ""
  - pref_label: "Registration Document"
    description: ""
  - pref_label: "Acquisition Paperwork"
    description: ""
  - pref_label: "Administrative"
    description: ""
  - pref_label: "Curatorial Document"
    description: ""
  - pref_label: "Deaccession Document"
    description: ""
  - pref_label: "Publications Document"
    description: ""
  - pref_label: "Conservation Document"
    description: ""
  - pref_label: "Marketing File"
    description: ""
  - pref_label: "Imaging"
    description: ""
  - pref_label: "Ryerson Library"
    description: ""
  - pref_label: "Design & Construction"
    description: ""
  - pref_label: "Museum Education"
    description: ""
  - pref_label: "Development"
    description: ""
  - pref_label: "Marketing (non-image)"
    description: ""
