pref_label: "View"
description: "Viewing angle, overall or detail, etc."
members:
  - pref_label: "Verso"
    description: ""
  - pref_label: "Recto"
    description: ""
  - pref_label: "Macro"
    description: ""
  - pref_label: "Micro"
    description: ""
  - pref_label: "Overall"
    description: ""
  - pref_label: "Detail"
    description: ""
  - pref_label: "Front"
    description: ""
  - pref_label: "Proper Right"
    description: ""
  - pref_label: "Back"
    description: ""
  - pref_label: "Proper Left"
    description: ""
  - pref_label: "Top"
    description: ""
  - pref_label: "Bottom"
    description: ""
