development:
  user: fedoraAdmin
  password: fedoraAdmin
  url: https://localhost:8443/fedora/rest
  base_path: /dev
test:
  user: fedoraAdmin
  password: fedoraAdmin
  url: https://localhost:8443/fedora/rest
  base_path: /test
production:
  user: fedoraAdmin
  password: fedoraAdmin
  url: https://localhost:8443/fedora/rest
  base_path: /prod
