development:
  admin:
    - aweadadmin
    - scossuadmin
    - citi
    - laketest
  api:
    - citi
    - combine
    - geneva
test:
  admin:
    - admin
    - apiuser
  api:
    - apiuser
production:
  admin:
    - aweadadmin
    - scossuadmin
  api:
    - apiuser
