# This is a sample config file that points to a solr server for each environment
development:
  url: http://localhost:8984/solr/aic_development
test:
  url: http://localhost:8985/solr/aic_test
production:
  url: http://your.production.server:8080/bl_solr/core0
